# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'calc.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(710, 629)
        self.calcLCD = QtWidgets.QLineEdit(Form)
        self.calcLCD.setGeometry(QtCore.QRect(50, 40, 611, 81))
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        self.calcLCD.setFont(font)
        self.calcLCD.setReadOnly(True)
        self.calcLCD.setObjectName("calcLCD")
        self.button_1 = QtWidgets.QPushButton(Form)
        self.button_1.setGeometry(QtCore.QRect(50, 160, 93, 81))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.button_1.setFont(font)
        self.button_1.setObjectName("button_1")
        self.button_2 = QtWidgets.QPushButton(Form)
        self.button_2.setGeometry(QtCore.QRect(190, 160, 93, 81))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.button_2.setFont(font)
        self.button_2.setObjectName("button_2")
        self.button_3 = QtWidgets.QPushButton(Form)
        self.button_3.setGeometry(QtCore.QRect(320, 160, 93, 81))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.button_3.setFont(font)
        self.button_3.setObjectName("button_3")
        self.button_4 = QtWidgets.QPushButton(Form)
        self.button_4.setGeometry(QtCore.QRect(50, 280, 93, 81))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.button_4.setFont(font)
        self.button_4.setObjectName("button_4")
        self.button_5 = QtWidgets.QPushButton(Form)
        self.button_5.setGeometry(QtCore.QRect(190, 280, 93, 81))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.button_5.setFont(font)
        self.button_5.setObjectName("button_5")
        self.button_6 = QtWidgets.QPushButton(Form)
        self.button_6.setGeometry(QtCore.QRect(320, 280, 93, 81))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.button_6.setFont(font)
        self.button_6.setObjectName("button_6")
        self.button_7 = QtWidgets.QPushButton(Form)
        self.button_7.setGeometry(QtCore.QRect(50, 390, 93, 81))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.button_7.setFont(font)
        self.button_7.setObjectName("button_7")
        self.button_8 = QtWidgets.QPushButton(Form)
        self.button_8.setGeometry(QtCore.QRect(190, 390, 93, 81))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.button_8.setFont(font)
        self.button_8.setObjectName("button_8")
        self.button_9 = QtWidgets.QPushButton(Form)
        self.button_9.setGeometry(QtCore.QRect(320, 390, 93, 81))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.button_9.setFont(font)
        self.button_9.setObjectName("button_9")
        self.button_0 = QtWidgets.QPushButton(Form)
        self.button_0.setGeometry(QtCore.QRect(50, 500, 93, 81))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.button_0.setFont(font)
        self.button_0.setObjectName("button_0")
        self.button_00 = QtWidgets.QPushButton(Form)
        self.button_00.setGeometry(QtCore.QRect(190, 500, 93, 81))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.button_00.setFont(font)
        self.button_00.setObjectName("button_00")
        self.button_dot = QtWidgets.QPushButton(Form)
        self.button_dot.setGeometry(QtCore.QRect(320, 500, 93, 81))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.button_dot.setFont(font)
        self.button_dot.setObjectName("button_dot")
        self.button_add = QtWidgets.QPushButton(Form)
        self.button_add.setGeometry(QtCore.QRect(450, 160, 93, 81))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.button_add.setFont(font)
        self.button_add.setObjectName("button_add")
        self.button_minus = QtWidgets.QPushButton(Form)
        self.button_minus.setGeometry(QtCore.QRect(450, 280, 93, 81))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.button_minus.setFont(font)
        self.button_minus.setObjectName("button_minus")
        self.button_mul = QtWidgets.QPushButton(Form)
        self.button_mul.setGeometry(QtCore.QRect(450, 390, 93, 81))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.button_mul.setFont(font)
        self.button_mul.setObjectName("button_mul")
        self.button_div = QtWidgets.QPushButton(Form)
        self.button_div.setGeometry(QtCore.QRect(450, 500, 93, 81))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.button_div.setFont(font)
        self.button_div.setObjectName("button_div")
        self.button_c = QtWidgets.QPushButton(Form)
        self.button_c.setGeometry(QtCore.QRect(570, 160, 93, 81))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.button_c.setFont(font)
        self.button_c.setObjectName("button_c")
        self.button_open = QtWidgets.QPushButton(Form)
        self.button_open.setGeometry(QtCore.QRect(570, 280, 93, 81))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.button_open.setFont(font)
        self.button_open.setObjectName("button_open")
        self.button_10 = QtWidgets.QPushButton(Form)
        self.button_10.setGeometry(QtCore.QRect(570, 390, 93, 81))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.button_10.setFont(font)
        self.button_10.setObjectName("button_10")
        self.button_11 = QtWidgets.QPushButton(Form)
        self.button_11.setGeometry(QtCore.QRect(570, 500, 93, 81))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.button_11.setFont(font)
        self.button_11.setObjectName("button_11")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Calculator"))
        self.button_1.setText(_translate("Form", "1"))
        self.button_2.setText(_translate("Form", "2"))
        self.button_3.setText(_translate("Form", "3"))
        self.button_4.setText(_translate("Form", "4"))
        self.button_5.setText(_translate("Form", "5"))
        self.button_6.setText(_translate("Form", "6"))
        self.button_7.setText(_translate("Form", "7"))
        self.button_8.setText(_translate("Form", "8"))
        self.button_9.setText(_translate("Form", "9"))
        self.button_0.setText(_translate("Form", "0"))
        self.button_00.setText(_translate("Form", "00"))
        self.button_dot.setText(_translate("Form", "."))
        self.button_add.setText(_translate("Form", "+"))
        self.button_minus.setText(_translate("Form", "-"))
        self.button_mul.setText(_translate("Form", "*"))
        self.button_div.setText(_translate("Form", "/"))
        self.button_c.setText(_translate("Form", "C"))
        self.button_open.setText(_translate("Form", "("))
        self.button_10.setText(_translate("Form", ")"))
        self.button_11.setText(_translate("Form", "="))
